### PR TITLE
[recnet-web] Refactor article recommendation flow

### PR DESCRIPTION
**Pull request by swh00tw**
## Description

New Rec Form and new flow to recommend paper.
- Auto-populate if article data found in db
- New flow to add new rec and edit rec

## Related Issue

#158 

## Notes

New edit rec flow ([link](https://www.notion.so/Editing-Rec-user-API-flow-249945d3a7fd44cbb5b244ba137427b7?pvs=4)):

Screenshot 2024-04-02 at 7 00 40 PM

## TODO

- [x] Paste the testing link: https://vercel.live/link/rec-net-git-refactor-rec-form-recnet-542617e7.vercel.app?via=deployment-domains-list-branch
- [x] Clear `console.log` or `console.error` for debug usage

### CODE REVIEW

**Comment by yoavartzi** [comment]
Can we remove "you think" ? Thanks!
image

**Comment by yoavartzi** [comment]
Recommend another article? -> Recommend a different paper? 

image

**Comment by yoavartzi** [comment]
image
Let change this text to:
Please enter the link to the paper. If this is an arXiv paper, please use the abstract page.

**Comment by yoavartzi** [comment]
The link format check is not ideal. It only checks for invalid/valid link when I act outside the box. So I have to act outside the box if I had put an invalid value to have the "next" button re-enabled.

**Comment by yoavartzi** [comment]
After "next" the text cursor should be in the appropriate box. If not paper -> title. if we retrieve details -> tldr.

Thanks!

**Comment by swh00tw** [comment]
Close this PR since Frontend migration is finished. Will fix above issues in #191

**Pull request closed without merging**
